### ISSUE TITLE
[brainstorm] how to automatically bump the version.rb

### ISSUE THREAD

**Issue by meleu** [mattbrictson/gem#173]
First of all: thanks for sharing this template!

I've been working in an internal CLI tool at job and noticed that I reached a similar result! 🙂 

I also use the release-drafter to automate the release notes and the versioning in the repository.

One thing I didn't get solved yet, though: **automatically** bumping the version inside the `lib/GEM_NAME/version.rb` file.

I initially solved it with a GitHub action to do both:

- actually release a "release draft" in GitHub.
- bump the `version.rb` using the version number from GitHub release.

(the GH action is at the end of this post)

Such technique was working pretty well! But if I protect the `main` branch, the GitHub action is not able to commit and push the change bumping the `version.rb` (which is expected, of course).

As I want the project to get more contributors, I want to protect the main branch, but I also would like to automate the gem version bumping...

Do you have any idea about how to automate this process?

**Note**: feel free to close this issue if you think it's unrelated with your project.

---

```yaml
# .github/workflows/bump_version.yml
name: Publish New Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      # needed to bump the gem version
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHA_PAT }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Set TAG var
        id: set_tag
        run: |
          TAG="$(gh release list | grep -m 1 Draft | cut -f 3)"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          if [[ -z "$TAG" ]]; then
            echo "No draft release found"
            exit 1
          fi

      - name: Configure git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

      - name: Publish a new Release on GitHub
        run: |
          TAG="${{ steps.set_tag.outputs.TAG }}"
          echo "Publishing release '$TAG'"
          gh release view "$TAG"
          if [[ ${GITHUB_REF} == 'refs/heads/main' ]]; then
            gh release edit "$TAG" --draft=false
          else
            echo "dry run (branch: ${GITHUB_REF})"
            echo gh release edit "$TAG" --draft=false
          fi

      # this step fails when the main branch is protected
      - name: Bump Gem Version
        run: |
          TAG="${{ steps.set_tag.outputs.TAG }}"
          echo "${GITHUB_ACTOR} is bumping the gem version to $TAG"
          gem install gem-release
          if [[ ${GITHUB_REF} == 'refs/heads/main' ]]; then
            gem bump --skip-ci --push --version "$TAG"
          else
            echo "dry run (branch: ${GITHUB_REF})"
            gem bump --pretend --skip-ci --push --version "$TAG"
          fi

```
